### ISSUE TITLE
expected name or number with <your-user>

### ISSUE THREAD

**Issue by simonkulessa** [devnope/ansible-workadventure#3]
Hi,

when executing the playbook, I always get the following error:

fatal: [localhost]: FAILED! => {
    "msg": "template error while templating string: expected name or number. String: {{ users.<your-user> }}"

`---`
`users:`
  `<your-user> :`
   ` username: "myuser"`
   ` pass: "mypassword"`
   ` shell: "/usr/bin/bash"`

It's been a while since I was using ansible, but my user configuration always looked different - So I'm quite confused about `<your-user>`. It seems that ansible is not using the vars.yml (I even tried the option with the group_vars directory).

What am I doing wrong?

Regards
Simon

**Comment by devnope** [comment]
Hello,

you replace <your-user> with the name in the vault-file.
Example:
in vault:
```
users:
  simon:
    username: "simonkulessa"
...
...
```
deployment.yml:
```
  tasks:
    - include_role:
        name: user_setup
      loop:
        - "{{ users.simon }}"
```

I did this, so you could easily add a second or third account, if necessary, if you share the instance with other people.
Then you could loop over
users.simon  
users.bernd  
users.alice  
users.hatice  
and so on you can easily distinguish, who gets set up. And users.name doesn't necessarily equal the unix-username.

I thought, that the <> would be helpful to clarify between prepared data and stuff that has to be set up manually.

Was I able to help you with this?

**Comment by devnope** [comment]
I'll close this issue due to lacking response. I hope it works for you.
