### ISSUE TITLE
error template error while templating: string unexpected name or number

### ISSUE THREAD

**Issue by miik-miik** [devnope/ansible-workadventure#5]
Hey Hey,
thanks for this repository! I try to host my own workadventure and follow along the readme - but then i'm deploy the ansbile part, i get the error: 

fatal: [localhost]: FAILED! => {"msg": "template error while templating string: unexpected name or number. String: {{users.<your-user> }}"}

in the deployment.yml I change the workdadventure_domain and leave the start room and jitsi url. Do i have to change something else there?

thanks in advance,
miik

**Comment by devnope** [comment]
please check the deployment.yml about line 21 `        - "{{ users.<your-user> }}"`
